### ISSUE TITLE
Placeholder for issues on new documentation

### ISSUE THREAD

**Issue by adityasood** [gocd/new-docs.gocd.org#5]
1. - [x] Change Go Tour to GoCD Tour at https://gocd.github.io/new-docs.gocd.org/current/navigation.html
2. - [x] Reduce white spacing on the left of the menu. Today id we scroll on the left the content is scrolled and not the menu.
3. - [x] Need bold highlighting on 'h3' tag
4. - [x] Allign the GoCD logo and first heading on the page
5. - [x] Reduce image size (https://gocd.github.io/new-docs.gocd.org/current/installation/install/server/osx.html) and https://gocd.github.io/new-docs.gocd.org/current/installation/install/server/osx.html
6. - [x] Fix styling for tables, currently tables do not have any borders.
7. - [x] Highlight the current page selection
8. - [ ] ~~Content here (https://gocd.github.io/new-docs.gocd.org/current/configuration/managing_environments.html) still shows the old environments tab.~~
9. - ~~[ ] Changes images here (https://gocd.github.io/new-docs.gocd.org/current/configuration/admin_use_custom_pipeline_label.html) to show the latest Admin tab~~
10. - [x] Last image here (https://gocd.github.io/new-docs.gocd.org/current/configuration/admin_add_task.html) needs alignment.
11. - [x] Size for Notifications Image here (https://gocd.github.io/new-docs.gocd.org/current/configuration/dev_notifications.html)
12. - [x] Can we see how we can reduce the number of scrolls here (https://gocd.github.io/new-docs.gocd.org/current/configuration/configuration_reference.html). Currently, there are 4.
13. - [x] Shell commands styling is broken (https://gocd.github.io/new-docs.gocd.org/current/advanced_usage/admin_install_multiple_agents.html)
14. - [x] One fo the shell commands on this page is commented. Can we look at differentating these? (https://gocd.github.io/new-docs.gocd.org/current/advanced_usage/command_repository.html)
15. - [x] Styling for 'Note' is not honored here (https://gocd.github.io/new-docs.gocd.org/current/advanced_usage/maintenance_mode.html)
16. - [ ] ~~Link redirection is broken here (https://gocd.github.io/new-docs.gocd.org/current/extension_points/notification_extension.html)~~
17. - [x] Add padding to the content section to align it better
18. - [x] Avoid refreshing the table when a section is clicked
19. - [x] For each section such as (https://new-docs.gocd.org/current/release_history.html) align the content to center and bold the content
20. - [x] Remove table padding
21. - [x] Fix the TOC map, it is broken in places like https://new-docs.gocd.org/current/configuration/configuration_reference.html. Maybe configure it to hold only certain tags like h1-2-3
22. - [x] Align GoCD logo, content and TOC
23. - [x] Highlight all headings h1-2-3
24. - [x] Fix the note blockquote here (https://new-docs.gocd.org/current/installation/install/agent/linux.html#configuring-the-go-agent)

**Comment by SanjanaB** [comment]
2,4,5 seems to be the same issue. Styling on h3 missing. Will merge them to a single item.

**Comment by SanjanaB** [comment]
Are we updating the docs content to have latest images or leaving them for next release? Saw some discussion happening on slack. @adityasood

**Comment by SanjanaB** [comment]
Created a separate issue to track 16. This requires a setup to be done on the existing bucket as well. Striking it off.

**Comment by SanjanaB** [comment]
Issue 7 is not supported by the theme. Raised an issue on the hugo-book project. Creating a separate issue to track it.

**Comment by adityasood** [comment]
Closing this issue, verified the docs for all the issues listed about. Issues related to content change will be listed separately in the docs repo.
